# Soal 11.12

Persamaan perlu disusun ulang agar elemen diagonal dominan: baris untuk `x1`, `x2`, dan `x3` dipilih dari persamaan kedua, ketiga, dan pertama.

In [1]:
import numpy as np
np.set_printoptions(precision=6, suppress=True)

def gauss_seidel(A, b, x0=None, es=5.0, max_iter=100, lam=1.0):
    A = np.array(A, dtype=float)
    b = np.array(b, dtype=float)
    n = len(b)
    x = np.zeros(n) if x0 is None else np.array(x0, dtype=float)
    rows = []
    for it in range(1, max_iter + 1):
        old = x.copy()
        for i in range(n):
            raw = (b[i] - np.dot(A[i, :i], x[:i]) - np.dot(A[i, i + 1:], old[i + 1:])) / A[i, i]
            x[i] = lam * raw + (1 - lam) * old[i]
        ea = np.full(n, np.nan)
        mask = x != 0
        ea[mask] = np.abs((x[mask] - old[mask]) / x[mask]) * 100
        rows.append([it, *x, np.nanmax(ea)])
        if np.nanmax(ea) < es:
            break
    return x, np.array(rows)

def jacobi(A, b, x0=None, es=5.0, max_iter=100):
    A = np.array(A, dtype=float)
    b = np.array(b, dtype=float)
    n = len(b)
    x = np.zeros(n) if x0 is None else np.array(x0, dtype=float)
    rows = []
    for it in range(1, max_iter + 1):
        old = x.copy()
        for i in range(n):
            x[i] = (b[i] - np.dot(A[i, :i], old[:i]) - np.dot(A[i, i + 1:], old[i + 1:])) / A[i, i]
        ea = np.full(n, np.nan)
        mask = x != 0
        ea[mask] = np.abs((x[mask] - old[mask]) / x[mask]) * 100
        rows.append([it, *x, np.nanmax(ea)])
        if np.nanmax(ea) < es:
            break
    return x, np.array(rows)

A_original = np.array([[-3, 1, 12], [6, -1, -1], [6, 9, 1]], float)
b_original = np.array([50, 3, 40], float)
order = [1, 2, 0]
A = A_original[order]
b = b_original[order]
x_plain, hist_plain = gauss_seidel(A, b, es=5, lam=1.0)
x_relax, hist_relax = gauss_seidel(A, b, es=5, lam=0.95)
print("A tersusun ulang=\n", A)
print("tanpa relaksasi x=", x_plain)
print("histori tanpa relaksasi=\n", hist_plain)
print("lambda=0.95 x=", x_relax)
print("histori lambda=0.95=\n", hist_relax)
print("solusi eksak =", np.linalg.solve(A_original, b_original))

A tersusun ulang=
 [[ 6. -1. -1.]
 [ 6.  9.  1.]
 [-3.  1. 12.]]
tanpa relaksasi x= [1.696789 2.829356 4.355084]
histori tanpa relaksasi=
 [[  1.         0.5        4.111111   3.949074 100.      ]
 [  2.         1.843364   2.776749   4.396112  72.87568 ]
 [  3.         1.695477   2.82567    4.355063   8.722465]
 [  4.         1.696789   2.829356   4.355084   0.130287]]
lambda=0.95 x= [1.709692 2.830032 4.356408]
histori lambda=0.95=
 [[  1.         0.475      3.921389   3.760703 100.      ]
 [  2.         1.715081   2.935111   4.321337  72.304517]
 [  3.         1.709692   2.830032   4.356408   3.712986]]
solusi eksak = [1.697368 2.828947 4.355263]


Penyusunan ulang membuat iterasi lebih stabil. Nilai `lambda=0.95` adalah underrelaxation sehingga koreksi tiap iterasi dibuat sedikit lebih kecil.