# Soal 11.16

Hitung solusi, invers, dan condition number berbasis row-sum norm (`inf` norm) tanpa scaling.

In [1]:
import numpy as np
np.set_printoptions(precision=6, suppress=True)

matrices = {
    "a": (np.array([[1, 4, 9], [4, 9, 16], [9, 16, 25]], float), np.array([14, 29, 50], float)),
    "b": (np.array([[1, 4, 9, 16], [4, 9, 16, 25], [9, 16, 25, 36], [16, 25, 36, 49]], float), np.array([30, 54, 86, 126], float)),
}
for label, (A, b) in matrices.items():
    n = A.shape[0]
    rank = np.linalg.matrix_rank(A)
    cond_inf = np.linalg.cond(A, p=np.inf)
    x_expected = np.ones(n)
    print("\nBagian", label)
    print("rank =", rank, "dari", n)
    print("A @ ones =", A @ x_expected)
    print("condition number row-sum =", cond_inf)

    if rank == n:
        invA = np.linalg.inv(A)
        x = np.linalg.solve(A, b)
        print("x =", x)
        print("A^-1 =\n", invA)
    else:
        print("Matriks singular/defisien rank, sehingga invers sejati tidak ada.")
        print("Salah satu solusi yang memenuhi soal adalah x =", x_expected)
        print("residual untuk x=ones =", A @ x_expected - b)
        print("Pseudoinverse Moore-Penrose =\n", np.linalg.pinv(A))



Bagian a
rank = 3 dari 3
A @ ones = [14. 29. 50.]
condition number row-sum = 750.0000000000026
x = [1. 1. 1.]
A^-1 =
 [[ 3.875 -5.5    2.125]
 [-5.5    7.    -2.5  ]
 [ 2.125 -2.5    0.875]]

Bagian b
rank = 3 dari 4
A @ ones = [ 30.  54.  86. 126.]
condition number row-sum = 1.4186338826217053e+17
Matriks singular/defisien rank, sehingga invers sejati tidak ada.
Salah satu solusi yang memenuhi soal adalah x = [1. 1. 1. 1.]
residual untuk x=ones = [0. 0. 0. 0.]
Pseudoinverse Moore-Penrose =
 [[ 1.61375 -1.02875 -1.25875  0.92375]
 [-1.02875  0.52375  0.71375 -0.45875]
 [-1.25875  0.71375  0.92375 -0.62875]
 [ 0.92375 -0.45875 -0.62875  0.41375]]


Solusi semua `x` seharusnya satu karena ruas kanan adalah jumlah tiap baris. Bagian (b) memberi pelajaran penting: matriks 4x4 sangat ill-conditioned dan terdeteksi defisien rank, sehingga invers sejati tidak stabil/tidak ada secara numerik. Karena itu `x = ones` diverifikasi langsung melalui `A @ ones = b`.
