# Soal 11.11

Sistem linear diselesaikan dengan Gauss-Seidel sampai persen galat relatif aproksimasi turun di bawah `5%`.

In [1]:
import numpy as np
np.set_printoptions(precision=6, suppress=True)

def gauss_seidel(A, b, x0=None, es=5.0, max_iter=100, lam=1.0):
    A = np.array(A, dtype=float)
    b = np.array(b, dtype=float)
    n = len(b)
    x = np.zeros(n) if x0 is None else np.array(x0, dtype=float)
    rows = []
    for it in range(1, max_iter + 1):
        old = x.copy()
        for i in range(n):
            raw = (b[i] - np.dot(A[i, :i], x[:i]) - np.dot(A[i, i + 1:], old[i + 1:])) / A[i, i]
            x[i] = lam * raw + (1 - lam) * old[i]
        ea = np.full(n, np.nan)
        mask = x != 0
        ea[mask] = np.abs((x[mask] - old[mask]) / x[mask]) * 100
        rows.append([it, *x, np.nanmax(ea)])
        if np.nanmax(ea) < es:
            break
    return x, np.array(rows)

def jacobi(A, b, x0=None, es=5.0, max_iter=100):
    A = np.array(A, dtype=float)
    b = np.array(b, dtype=float)
    n = len(b)
    x = np.zeros(n) if x0 is None else np.array(x0, dtype=float)
    rows = []
    for it in range(1, max_iter + 1):
        old = x.copy()
        for i in range(n):
            x[i] = (b[i] - np.dot(A[i, :i], old[:i]) - np.dot(A[i, i + 1:], old[i + 1:])) / A[i, i]
        ea = np.full(n, np.nan)
        mask = x != 0
        ea[mask] = np.abs((x[mask] - old[mask]) / x[mask]) * 100
        rows.append([it, *x, np.nanmax(ea)])
        if np.nanmax(ea) < es:
            break
    return x, np.array(rows)

A = np.array([[10, 2, -1], [-3, -6, 2], [1, 1, 5]], float)
b = np.array([27, -61.5, -21.5], float)
x, hist = gauss_seidel(A, b, es=5)
print("x =", x)
print("riwayat [iter, x1, x2, x3, ea_maks] =\n", hist)
print("solusi eksak =", np.linalg.solve(A, b))

x = [ 0.500253  8.000112 -6.000073]
riwayat [iter, x1, x2, x3, ea_maks] =
 [[  1.         2.7        8.9       -6.62     100.      ]
 [  2.         0.258      7.914333  -5.934467 946.511628]
 [  3.         0.523687   8.010001  -6.006738  50.733899]
 [  4.         0.497326   7.999091  -5.999283   5.300476]
 [  5.         0.500253   8.000112  -6.000073   0.585185]]
solusi eksak = [ 0.5  8.  -6. ]


Urutan persamaan sudah cocok untuk iterasi karena diagonal relatif besar dibanding elemen lainnya pada tiap baris.