# Soal 11.13

Persamaan disusun ulang untuk memperbesar dominasi diagonal: baris untuk `x1`, `x2`, `x3` diambil dari persamaan ketiga, pertama, kedua.

In [1]:
import numpy as np
np.set_printoptions(precision=6, suppress=True)

def gauss_seidel(A, b, x0=None, es=5.0, max_iter=100, lam=1.0):
    A = np.array(A, dtype=float)
    b = np.array(b, dtype=float)
    n = len(b)
    x = np.zeros(n) if x0 is None else np.array(x0, dtype=float)
    rows = []
    for it in range(1, max_iter + 1):
        old = x.copy()
        for i in range(n):
            raw = (b[i] - np.dot(A[i, :i], x[:i]) - np.dot(A[i, i + 1:], old[i + 1:])) / A[i, i]
            x[i] = lam * raw + (1 - lam) * old[i]
        ea = np.full(n, np.nan)
        mask = x != 0
        ea[mask] = np.abs((x[mask] - old[mask]) / x[mask]) * 100
        rows.append([it, *x, np.nanmax(ea)])
        if np.nanmax(ea) < es:
            break
    return x, np.array(rows)

def jacobi(A, b, x0=None, es=5.0, max_iter=100):
    A = np.array(A, dtype=float)
    b = np.array(b, dtype=float)
    n = len(b)
    x = np.zeros(n) if x0 is None else np.array(x0, dtype=float)
    rows = []
    for it in range(1, max_iter + 1):
        old = x.copy()
        for i in range(n):
            x[i] = (b[i] - np.dot(A[i, :i], old[:i]) - np.dot(A[i, i + 1:], old[i + 1:])) / A[i, i]
        ea = np.full(n, np.nan)
        mask = x != 0
        ea[mask] = np.abs((x[mask] - old[mask]) / x[mask]) * 100
        rows.append([it, *x, np.nanmax(ea)])
        if np.nanmax(ea) < es:
            break
    return x, np.array(rows)

A_original = np.array([[2, -6, -1], [-3, -1, 7], [-8, 1, -2]], float)
b_original = np.array([-38, -34, -20], float)
order = [2, 0, 1]
A = A_original[order]
b = b_original[order]
x_plain, hist_plain = gauss_seidel(A, b, es=5, lam=1.0)
x_relax, hist_relax = gauss_seidel(A, b, es=5, lam=1.2)
print("A tersusun ulang=\n", A)
print("tanpa relaksasi x=", x_plain)
print("histori tanpa relaksasi=\n", hist_plain)
print("lambda=1.2 x=", x_relax)
print("histori lambda=1.2=\n", hist_relax)
print("solusi eksak =", np.linalg.solve(A_original, b_original))

A tersusun ulang=
 [[-8.  1. -2.]
 [ 2. -6. -1.]
 [-3. -1.  7.]]
tanpa relaksasi x= [ 4.004659  7.99168  -1.999192]
histori tanpa relaksasi=
 [[  1.         2.5        7.166667  -2.761905 100.      ]
 [  2.         4.08631    8.155754  -1.94076   42.310501]
 [  3.         4.004659   7.99168   -1.999192   2.922791]]
lambda=1.2 x= [ 4.012225  8.027261 -1.979007]
histori lambda=1.2=
 [[  1.         3.         8.8       -2.777143 100.      ]
 [  2.         4.553143   8.216686  -1.522952  82.352638]
 [  3.         3.77876    7.772757  -2.248146  32.257438]
 [  4.         4.084605   8.12892   -1.884759  19.280313]
 [  5.         3.967845   7.938306  -2.050162   8.067789]
 [  6.         4.012225   8.027261  -1.979007   3.595466]]
solusi eksak = [ 4.  8. -2.]


Overrelaxation `lambda=1.2` mempercepat koreksi jika sistem tetap konvergen. Hasil dibandingkan dengan solusi langsung NumPy.