# Soal 11.14

Jika dua garis pada ilustrasi Gauss-Seidel memiliki kemiringan `1` dan `-1`, faktor iterasi memiliki magnitudo sekitar `1`. Akibatnya iterasi tidak meredam kesalahan.

In [1]:
import numpy as np
np.set_printoptions(precision=6, suppress=True)

# Contoh sederhana dua garis dengan slope +1 dan -1:
# y = x dan y = -x + 2 berpotongan di (1, 1).
# Iterasi koordinat yang bolak-balik pada dua garis akan memantul, bukan mendekat secara stabil.
pts = []
x, y = 0.0, 0.0
for k in range(6):
    y = x          # garis slope +1
    x = 2 - y      # garis slope -1
    pts.append((k + 1, x, y))
print("iterasi ilustratif (iter, x, y):")
print(np.array(pts))

iterasi ilustratif (iter, x, y):
[[1. 2. 0.]
 [2. 0. 2.]
 [3. 2. 0.]
 [4. 0. 2.]
 [5. 2. 0.]
 [6. 0. 2.]]


Kesimpulannya, Gauss-Seidel mengalami osilasi/memantul antar garis dan tidak konvergen menuju titik potong secara stabil.