# Soal 11.22

Persamaan diubah menjadi bentuk matriks `A x = b`, lalu dihitung solusi, transpose, dan invers koefisien.

In [1]:
import numpy as np
np.set_printoptions(precision=6, suppress=True)

A = np.array([[0, -7, 5], [0, 4, 7], [-4, 3, -7]], float)
b = np.array([50, -30, 40], float)
x = np.linalg.solve(A, b)
print("A=\n", A)
print("b=", b)
print("x=", x)
print("A.T=\n", A.T)
print("A^-1=\n", np.linalg.inv(A))
print("cek A@x=", A @ x)

A=
 [[ 0. -7.  5.]
 [ 0.  4.  7.]
 [-4.  3. -7.]]
b= [ 50. -30.  40.]
x= [-15.181159  -7.246377  -0.144928]
A.T=
 [[ 0.  0. -4.]
 [-7.  4.  3.]
 [ 5.  7. -7.]]
A^-1=
 [[-0.177536 -0.123188 -0.25    ]
 [-0.101449  0.072464 -0.      ]
 [ 0.057971  0.101449  0.      ]]
cek A@x= [ 50. -30.  40.]


Bentuk matriks dipilih setelah semua variabel diletakkan di kiri dan konstanta di kanan.