# Soal 11.2

Diminta invers matriks Example 11.1 berdasarkan dekomposisi LU dan vektor satuan. Matriks Example 11.1 adalah tridiagonal dengan diagonal utama `2.04` dan diagonal samping `-1`.

In [1]:
import numpy as np
np.set_printoptions(precision=6, suppress=True)

def thomas(a, d, c, b):
    a = np.array(a, dtype=float)
    d = np.array(d, dtype=float)
    c = np.array(c, dtype=float)
    b = np.array(b, dtype=float)
    n = len(d)
    l = np.zeros(n - 1)
    u = d.copy()
    r = b.copy()
    for i in range(1, n):
        l[i - 1] = a[i - 1] / u[i - 1]
        u[i] = u[i] - l[i - 1] * c[i - 1]
        r[i] = r[i] - l[i - 1] * r[i - 1]
    x = np.zeros(n)
    x[-1] = r[-1] / u[-1]
    for i in range(n - 2, -1, -1):
        x[i] = (r[i] - c[i] * x[i + 1]) / u[i]
    L = np.eye(n)
    U = np.zeros((n, n))
    for i in range(n):
        U[i, i] = u[i]
        if i < n - 1:
            L[i + 1, i] = l[i]
            U[i, i + 1] = c[i]
    return L, U, r, x

A = np.array([[2.04, -1, 0, 0], [-1, 2.04, -1, 0], [0, -1, 2.04, -1], [0, 0, -1, 2.04]], float)
L, U, _, _ = thomas([-1, -1, -1], [2.04]*4, [-1, -1, -1], [40.8, 0.8, 0.8, 200.8])

def solve_lu(L, U, b):
    y = np.zeros_like(b, dtype=float)
    for i in range(len(b)):
        y[i] = b[i] - np.dot(L[i, :i], y[:i])
    x = np.zeros_like(b, dtype=float)
    for i in range(len(b)-1, -1, -1):
        x[i] = (y[i] - np.dot(U[i, i+1:], x[i+1:])) / U[i, i]
    return x

I = np.eye(4)
A_inv = np.column_stack([solve_lu(L, U, I[:, j]) for j in range(4)])
print("L=\n", L)
print("U=\n", U)
print("A^-1 dari LU=\n", A_inv)
print("Cek A @ A^-1=\n", A @ A_inv)

L=
 [[ 1.        0.        0.        0.      ]
 [-0.490196  1.        0.        0.      ]
 [ 0.       -0.645243  1.        0.      ]
 [ 0.        0.       -0.716971  1.      ]]
U=
 [[ 2.04     -1.        0.        0.      ]
 [ 0.        1.549804 -1.        0.      ]
 [ 0.        0.        1.394757 -1.      ]
 [ 0.        0.        0.        1.323029]]
A^-1 dari LU=
 [[0.755841 0.541916 0.349667 0.171406]
 [0.541916 1.105509 0.713322 0.349667]
 [0.349667 0.713322 1.105509 0.541916]
 [0.171406 0.349667 0.541916 0.755841]]
Cek A @ A^-1=
 [[ 1.  0.  0.  0.]
 [-0.  1.  0.  0.]
 [-0.  0.  1.  0.]
 [-0. -0.  0.  1.]]


Setiap kolom invers diperoleh dengan menyelesaikan `L y = e_j`, lalu `U x = y`. Produk `A @ A_inv` mendekati matriks identitas, sehingga invers valid.