# Soal 11.20

Ulangi analisis condition number untuk matriks Vandermonde 6 dimensi dengan `x = [4, 2, 7, 10, 3, 5]`.

In [1]:
import numpy as np
np.set_printoptions(precision=6, suppress=True)

points = np.array([4, 2, 7, 10, 3, 5], float)
V = np.vander(points, N=6, increasing=True)
b = V.sum(axis=1)
x = np.linalg.solve(V, b)
cond2 = np.linalg.cond(V, p=2)
lost_digits = np.log10(cond2)
print("V=\n", V)
print("cond2 =", cond2)
print("perkiraan digit hilang =", lost_digits)
print("x =", x)
print("error absolut maksimum =", np.max(np.abs(x - 1)))

V=
 [[     1.      4.     16.     64.    256.   1024.]
 [     1.      2.      4.      8.     16.     32.]
 [     1.      7.     49.    343.   2401.  16807.]
 [     1.     10.    100.   1000.  10000. 100000.]
 [     1.      3.      9.     27.     81.    243.]
 [     1.      5.     25.    125.    625.   3125.]]
cond2 = 14491732.137784017
perkiraan digit hilang = 7.161120298026216
x = [1. 1. 1. 1. 1. 1.]
error absolut maksimum = 3.9501513171558145e-11


Matriks Vandermonde juga cenderung ill-conditioned, terutama saat nilai titik tersebar. Ruas kanan jumlah baris membuat solusi eksak ideal berupa semua satu.