# Soal 11.4

Validasi dekomposisi Cholesky Example 11.2 dilakukan dengan menghitung `L @ L.T` dan membandingkannya dengan `A`.

In [1]:
import numpy as np
np.set_printoptions(precision=6, suppress=True)

def cholesky_lower(A):
    A = np.array(A, dtype=float)
    n = A.shape[0]
    L = np.zeros_like(A)
    for k in range(n):
        for i in range(k):
            L[k, i] = (A[k, i] - np.dot(L[k, :i], L[i, :i])) / L[i, i]
        L[k, k] = np.sqrt(A[k, k] - np.dot(L[k, :k], L[k, :k]))
    return L

def forward_substitution(L, b):
    b = np.array(b, dtype=float)
    y = np.zeros_like(b)
    for i in range(len(b)):
        y[i] = (b[i] - np.dot(L[i, :i], y[:i])) / L[i, i]
    return y

def back_substitution(U, y):
    y = np.array(y, dtype=float)
    x = np.zeros_like(y)
    for i in range(len(y) - 1, -1, -1):
        x[i] = (y[i] - np.dot(U[i, i + 1:], x[i + 1:])) / U[i, i]
    return x

A = np.array([[6, 15, 55], [15, 55, 225], [55, 225, 979]], float)
L = cholesky_lower(A)
print("L=\n", L)
print("L @ L.T=\n", L @ L.T)
print("Selisih=\n", L @ L.T - A)

L=
 [[ 2.44949   0.        0.      ]
 [ 6.123724  4.1833    0.      ]
 [22.453656 20.916501  6.110101]]
L @ L.T=
 [[  6.  15.  55.]
 [ 15.  55. 225.]
 [ 55. 225. 979.]]
Selisih=
 [[-0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


Selisih numerik bernilai nol sampai galat pembulatan, sehingga dekomposisi memenuhi `A = L L^T`.