# Soal 11.6

Dekomposisi Cholesky untuk sistem simetris 3x3 dan penggunaannya untuk menyelesaikan `x`.

In [1]:
import numpy as np
np.set_printoptions(precision=6, suppress=True)

def cholesky_lower(A):
    A = np.array(A, dtype=float)
    n = A.shape[0]
    L = np.zeros_like(A)
    for k in range(n):
        for i in range(k):
            L[k, i] = (A[k, i] - np.dot(L[k, :i], L[i, :i])) / L[i, i]
        L[k, k] = np.sqrt(A[k, k] - np.dot(L[k, :k], L[k, :k]))
    return L

def forward_substitution(L, b):
    b = np.array(b, dtype=float)
    y = np.zeros_like(b)
    for i in range(len(b)):
        y[i] = (b[i] - np.dot(L[i, :i], y[:i])) / L[i, i]
    return y

def back_substitution(U, y):
    y = np.array(y, dtype=float)
    x = np.zeros_like(y)
    for i in range(len(y) - 1, -1, -1):
        x[i] = (y[i] - np.dot(U[i, i + 1:], x[i + 1:])) / U[i, i]
    return x

A = np.array([[8, 20, 15], [20, 80, 50], [15, 50, 60]], float)
b = np.array([100, 250, 100], float)
L = cholesky_lower(A)
y = forward_substitution(L, b)
x = back_substitution(L.T, y)
print("L=\n", L)
print("L @ L.T=\n", L @ L.T)
print("x =", x)

L=
 [[2.828427 0.       0.      ]
 [7.071068 5.477226 0.      ]
 [5.303301 2.282177 5.163978]]
L @ L.T=
 [[ 8. 20. 15.]
 [20. 80. 50.]
 [15. 50. 60.]]
x = [15.234375  1.367188 -3.28125 ]


Karena `A` simetris positif definit, Cholesky dapat digunakan tanpa pivoting. Produk `L L^T` mengembalikan matriks koefisien.