# Soal 11.7

Matriks diagonal positif memiliki dekomposisi Cholesky yang sangat sederhana: akar kuadrat setiap elemen diagonal.

In [1]:
import numpy as np
np.set_printoptions(precision=6, suppress=True)

def cholesky_lower(A):
    A = np.array(A, dtype=float)
    n = A.shape[0]
    L = np.zeros_like(A)
    for k in range(n):
        for i in range(k):
            L[k, i] = (A[k, i] - np.dot(L[k, :i], L[i, :i])) / L[i, i]
        L[k, k] = np.sqrt(A[k, k] - np.dot(L[k, :k], L[k, :k]))
    return L

def forward_substitution(L, b):
    b = np.array(b, dtype=float)
    y = np.zeros_like(b)
    for i in range(len(b)):
        y[i] = (b[i] - np.dot(L[i, :i], y[:i])) / L[i, i]
    return y

def back_substitution(U, y):
    y = np.array(y, dtype=float)
    x = np.zeros_like(y)
    for i in range(len(y) - 1, -1, -1):
        x[i] = (y[i] - np.dot(U[i, i + 1:], x[i + 1:])) / U[i, i]
    return x

A = np.diag([9.0, 25.0, 4.0])
L = cholesky_lower(A)
print("L=\n", L)
print("L @ L.T=\n", L @ L.T)

L=
 [[3. 0. 0.]
 [0. 5. 0.]
 [0. 0. 2.]]
L @ L.T=
 [[ 9.  0.  0.]
 [ 0. 25.  0.]
 [ 0.  0.  4.]]


Hasilnya `L = diag(3, 5, 2)`. Ini sesuai dengan rumus Cholesky karena semua elemen luar diagonal nol.