# Soal 11.8

Sistem dari Soal 11.1 diselesaikan dengan Gauss-Seidel memakai overrelaxation `lambda = 1.2` dan toleransi `es = 5%`.

In [1]:
import numpy as np
np.set_printoptions(precision=6, suppress=True)

def gauss_seidel(A, b, x0=None, es=5.0, max_iter=100, lam=1.0):
    A = np.array(A, dtype=float)
    b = np.array(b, dtype=float)
    n = len(b)
    x = np.zeros(n) if x0 is None else np.array(x0, dtype=float)
    rows = []
    for it in range(1, max_iter + 1):
        old = x.copy()
        for i in range(n):
            raw = (b[i] - np.dot(A[i, :i], x[:i]) - np.dot(A[i, i + 1:], old[i + 1:])) / A[i, i]
            x[i] = lam * raw + (1 - lam) * old[i]
        ea = np.full(n, np.nan)
        mask = x != 0
        ea[mask] = np.abs((x[mask] - old[mask]) / x[mask]) * 100
        rows.append([it, *x, np.nanmax(ea)])
        if np.nanmax(ea) < es:
            break
    return x, np.array(rows)

def jacobi(A, b, x0=None, es=5.0, max_iter=100):
    A = np.array(A, dtype=float)
    b = np.array(b, dtype=float)
    n = len(b)
    x = np.zeros(n) if x0 is None else np.array(x0, dtype=float)
    rows = []
    for it in range(1, max_iter + 1):
        old = x.copy()
        for i in range(n):
            x[i] = (b[i] - np.dot(A[i, :i], old[:i]) - np.dot(A[i, i + 1:], old[i + 1:])) / A[i, i]
        ea = np.full(n, np.nan)
        mask = x != 0
        ea[mask] = np.abs((x[mask] - old[mask]) / x[mask]) * 100
        rows.append([it, *x, np.nanmax(ea)])
        if np.nanmax(ea) < es:
            break
    return x, np.array(rows)

A = np.array([[0.8, -0.4, 0.0], [-0.4, 0.8, -0.4], [0.0, -0.4, 0.8]])
b = np.array([41.0, 25.0, 105.0])
x, hist = gauss_seidel(A, b, es=5, lam=1.2)
print("x dengan SOR lambda=1.2 =", x)
print("riwayat [iter, x1, x2, x3, ea_maks] =\n", hist)
print("solusi eksak =", np.linalg.solve(A, b))

x dengan SOR lambda=1.2 = [171.422976 244.388659 253.6222  ]
riwayat [iter, x1, x2, x3, ea_maks] =
 [[  1.        61.5       74.4      202.14     100.      ]
 [  2.        93.84     200.208    237.1968    62.838648]
 [  3.       162.8568   237.49056  252.554976  42.378826]
 [  4.       171.422976 244.388659 253.6222     4.997099]]
solusi eksak = [173.75 245.   253.75]


Overrelaxation memperbesar koreksi iterasi. Dengan `lambda=1.2`, iterasi tetap konvergen dan berhenti saat galat relatif aproksimasi maksimum kurang dari `5%`.