# Soal 11.9

Konsentrasi reaktor diselesaikan dengan Gauss-Seidel sampai `es < 5%`. Koefisien mengikuti PDF soal lokal.

In [1]:
import numpy as np
np.set_printoptions(precision=6, suppress=True)

def gauss_seidel(A, b, x0=None, es=5.0, max_iter=100, lam=1.0):
    A = np.array(A, dtype=float)
    b = np.array(b, dtype=float)
    n = len(b)
    x = np.zeros(n) if x0 is None else np.array(x0, dtype=float)
    rows = []
    for it in range(1, max_iter + 1):
        old = x.copy()
        for i in range(n):
            raw = (b[i] - np.dot(A[i, :i], x[:i]) - np.dot(A[i, i + 1:], old[i + 1:])) / A[i, i]
            x[i] = lam * raw + (1 - lam) * old[i]
        ea = np.full(n, np.nan)
        mask = x != 0
        ea[mask] = np.abs((x[mask] - old[mask]) / x[mask]) * 100
        rows.append([it, *x, np.nanmax(ea)])
        if np.nanmax(ea) < es:
            break
    return x, np.array(rows)

def jacobi(A, b, x0=None, es=5.0, max_iter=100):
    A = np.array(A, dtype=float)
    b = np.array(b, dtype=float)
    n = len(b)
    x = np.zeros(n) if x0 is None else np.array(x0, dtype=float)
    rows = []
    for it in range(1, max_iter + 1):
        old = x.copy()
        for i in range(n):
            x[i] = (b[i] - np.dot(A[i, :i], old[:i]) - np.dot(A[i, i + 1:], old[i + 1:])) / A[i, i]
        ea = np.full(n, np.nan)
        mask = x != 0
        ea[mask] = np.abs((x[mask] - old[mask]) / x[mask]) * 100
        rows.append([it, *x, np.nanmax(ea)])
        if np.nanmax(ea) < es:
            break
    return x, np.array(rows)

A = np.array([[15, -3, -1], [-3, 18, -6], [-4, -1, 12]], float)
b = np.array([3800, 1200, 2350], float)
x, hist = gauss_seidel(A, b, es=5)
print("c =", x)
print("riwayat [iter, c1, c2, c3, ea_maks] =\n", hist)
print("solusi eksak =", np.linalg.solve(A, b))

c = [319.325357 226.540187 321.153468]
riwayat [iter, c1, c2, c3, ea_maks] =
 [[  1.       253.333333 108.888889 289.351852 100.      ]
 [  2.       294.401235 212.184156 311.649091  48.681895]
 [  3.       316.546771 223.307492 319.957881   6.995976]
 [  4.       319.325357 226.540187 321.153468   1.426985]]
solusi eksak = [320.207254 227.202073 321.502591]


Matriks cukup dominan diagonal sehingga Gauss-Seidel konvergen dari tebakan nol.